# Generated by Django 5.2 on 2026-08-10 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_offres", "0001_initial"),
        ("app_users", "0002_entreprise_remove_profil_statut_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="offre",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offres",
                to="app_users.entreprise",
            ),
        ),
        migrations.RemoveField(
            model_name="competence",
            name="niveau",
        ),
        migrations.AddField(
            model_name="competence",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="competence",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="offre",
            name="competences",
            field=models.ManyToManyField(
                related_name="offres",
                through="app_offres.NiveauCompetenceOffre",
                to="app_offres.competence",
            ),
        ),
        migrations.AddField(
            model_name="offre",
            name="deviseSalaire",
            field=models.CharField(default="FCFA", max_length=10),
        ),
        migrations.AddField(
            model_name="offre",
            name="localisation",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="offre",
            name="salaireMax",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="offre",
            name="salaireMin",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="offre",
            name="statut",
            field=models.CharField(
                choices=[
                    ("brouillon", "Brouillon"),
                    ("en_attente", "En attente"),
                    ("publiee", "Publiée"),
                    ("suspendue", "Suspendue"),
                    ("expiree", "Expirée"),
                    ("fermee", "Fermée"),
                ],
                default="brouillon",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="competence",
            name="nom",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="niveaucompetenceoffre",
            name="competence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="niveaux_offres",
                to="app_offres.competence",
            ),
        ),
        migrations.AlterField(
            model_name="niveaucompetenceoffre",
            name="niveauRequis",
            field=models.CharField(
                choices=[
                    ("debutant", "Débutant"),
                    ("intermediaire", "Intermédiaire"),
                    ("avance", "Avancé"),
                    ("expert", "Expert"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="niveaucompetenceoffre",
            name="offre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="niveaux_competences",
                to="app_offres.offre",
            ),
        ),
        migrations.AlterField(
            model_name="offre",
            name="recruteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offres_publiees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="offre",
            name="typeOffre",
            field=models.CharField(
                choices=[
                    ("CDI", "CDI"),
                    ("CDD", "CDD"),
                    ("stage", "Stage"),
                    ("freelance", "Freelance"),
                    ("alternance", "Alternance"),
                    ("interim", "Intérim"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="niveaucompetenceoffre",
            constraint=models.UniqueConstraint(
                fields=("offre", "competence"), name="unique_competence_offre"
            ),
        ),
        migrations.DeleteModel(
            name="Entreprise",
        ),
    ]
