# Generated by Django 5.2 on 2026-07-14 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_offres", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateSoumission", models.DateTimeField(auto_now_add=True)),
                ("statut", models.CharField(default="En attente", max_length=50)),
                ("dateModification", models.DateTimeField(auto_now=True)),
                (
                    "candidat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatures",
                        to="app_offres.offre",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomFichier", models.CharField(max_length=200)),
                ("typeFichier", models.CharField(max_length=50)),
                ("contenu", models.FileField(upload_to="documents/%Y/%m/%d/")),
                ("taille", models.IntegerField(default=0)),
                ("lien", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="app_candidatures.candidature",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entretien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateHeure", models.DateTimeField()),
                ("type", models.CharField(max_length=50)),
                ("lieu", models.CharField(blank=True, max_length=200, null=True)),
                ("statut", models.CharField(default="Planifié", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entretiens",
                        to="app_candidatures.candidature",
                    ),
                ),
                (
                    "recruteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entretiens_animes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="candidature",
            constraint=models.UniqueConstraint(
                fields=("candidat", "offre"), name="unique_candidature_par_offre"
            ),
        ),
    ]
