# Generated by Django 5.2 on 2026-08-10 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, unique=True)),
                ("secteur", models.CharField(blank=True, max_length=100, null=True)),
                ("adresse", models.TextField(blank=True, null=True)),
                ("telephone", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("siteweb", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="entreprises/logos/"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("active", "Active"),
                            ("suspendue", "Suspendue"),
                            ("refusee", "Refusée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("verifiee", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="profil",
            name="statut",
        ),
        migrations.AddField(
            model_name="profil",
            name="anneesExperience",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profil",
            name="biographie",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profil",
            name="deviseTarif",
            field=models.CharField(default="FCFA", max_length=10),
        ),
        migrations.AddField(
            model_name="profil",
            name="disponibilite",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profil",
            name="fonction",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="profil",
            name="githubUrl",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profil",
            name="linkedinUrl",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profil",
            name="photoProfil",
            field=models.ImageField(blank=True, null=True, upload_to="profils/"),
        ),
        migrations.AddField(
            model_name="profil",
            name="portfolioUrl",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profil",
            name="statut_compte",
            field=models.CharField(
                choices=[
                    ("actif", "Actif"),
                    ("en_attente", "En attente"),
                    ("suspendu", "Suspendu"),
                    ("bloque", "Bloqué"),
                ],
                default="actif",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profil",
            name="statut_recruteur",
            field=models.CharField(
                choices=[
                    ("non_concerne", "Non concerné"),
                    ("en_attente", "En attente"),
                    ("verifie", "Vérifié"),
                    ("refuse", "Refusé"),
                    ("suspendu", "Suspendu"),
                ],
                default="non_concerne",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profil",
            name="tarifHoraire",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="profil",
            name="titreProfessionnel",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="profil",
            name="specialite",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="profil",
            name="telephone",
            field=models.CharField(
                blank=True, db_index=True, max_length=30, null=True, unique=True
            ),
        ),
        migrations.CreateModel(
            name="RecruteurEntreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fonction", models.CharField(blank=True, max_length=150, null=True)),
                ("principal", models.BooleanField(default=False)),
                ("actif", models.BooleanField(default=True)),
                ("dateAssociation", models.DateTimeField(auto_now_add=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associations_recruteurs",
                        to="app_users.entreprise",
                    ),
                ),
                (
                    "recruteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associations_entreprises",
                        to="app_users.profil",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profil",
            name="entreprises",
            field=models.ManyToManyField(
                blank=True,
                related_name="recruteurs",
                through="app_users.RecruteurEntreprise",
                to="app_users.entreprise",
            ),
        ),
        migrations.AddConstraint(
            model_name="recruteurentreprise",
            constraint=models.UniqueConstraint(
                fields=("recruteur", "entreprise"), name="unique_recruteur_entreprise"
            ),
        ),
    ]
